spring.application.name=jobapplication

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/job_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Actuators
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#info -> actuator
management.info.env.enabled=true
info.app.name=JobApplication
info.app.description=Job app built by codeX-Azhar
info.app.version=1.0.0

#graceful shutdown
management.endpoint.shutdown.enabled=true
server.shutdown=graceful